# application.yml

spring:
  profiles:
    active: dev
  application:
    name: email-service

staffjoy:
  common:
    sentry-dsn: ${SENTRY_DSN:https://80bbf4ae778b525f9fe72e2813cd5246@sentry.io/1271087}
    deploy-env: ${DEPLOY:V2}
  aliyun-access-key: ${ALIYUN_ACCESS_KEY}
  aliyun-access-secret: ${ALIYUN_ACCESS_SECRET}
