spring:
  datasource:
    url: jdbc:mysql://192.168.109.129:3308/staffjoy_account?useUnicode=true&characterEncoding=utf-8
    username: root
    password: test1234
  jpa:
    show-sql: true
server:
  port: 8081
staffjoy:
  email-service-endpoint: http://localhost:8088
  company-service-endpoint: http://localhost:8082
  bot-service-endpoint: http://localhost:8087
management:
  endpoints:
    web:
      exposure:
        include: "*"
