# application.yml

spring:
  profiles:
    active: dev
  application:
    name: ical-service

staffjoy:
  common:
    sentry-dsn: ${SENTRY_DSN:sentry-dsn:https://80bbf4ae778b525f9fe72e2813cd5246@sentry.io/1271087}
    deploy-env: ${DEPLOY:V2}
  company-service-endpoint: http://company-service:8080