---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '4'
    k8s.kuboard.cn/ingress: 'false'
    k8s.kuboard.cn/service: ClusterIP
    k8s.kuboard.cn/workload: account-service
  creationTimestamp: '2020-12-10T16:23:03Z'
  generation: 6
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: account-service
  name: account-service
  namespace: staffjoy
  resourceVersion: '628411'
  selfLink: /apis/apps/v1/namespaces/staffjoy/deployments/account-service
  uid: 446d6a24-d584-4e36-b1eb-b5dbcf975352
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: svc
      k8s.kuboard.cn/name: account-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2020-12-11T00:38:00+08:00'
      labels:
        k8s.kuboard.cn/layer: svc
        k8s.kuboard.cn/name: account-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: staffjoy-config
          image: 'registry.cn-hangzhou.aliyuncs.com/dypc/staffjoy-account-svc:1.0'
          imagePullPolicy: IfNotPresent
          name: staffjoy-account-svc
          ports:
            - containerPort: 80
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-12-11T09:26:11Z'
      lastUpdateTime: '2020-12-11T09:26:11Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-12-12T13:08:42Z'
      lastUpdateTime: '2020-12-12T13:08:42Z'
      message: ReplicaSet "account-service-55cc7dd78b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/workload: account-service
  creationTimestamp: '2020-12-10T16:23:03Z'
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: account-service
  name: account-service
  namespace: staffjoy
  resourceVersion: '534226'
  selfLink: /api/v1/namespaces/staffjoy/services/account-service
  uid: 8a2463db-3163-42b3-b0bb-be554e932571
spec:
  clusterIP: 10.244.156.231
  ports:
    - name: d7mexp
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: account-service
  sessionAffinity: None
  type: ClusterIP

