---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    k8s.kuboard.cn/ingress: 'false'
    k8s.kuboard.cn/service: ClusterIP
    k8s.kuboard.cn/workload: app-service
  creationTimestamp: '2020-12-12T14:39:50Z'
  generation: 1
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: app-service
  name: app-service
  namespace: staffjoy
  resourceVersion: '629616'
  selfLink: /apis/apps/v1/namespaces/staffjoy/deployments/app-service
  uid: 6cedc5ba-b347-4f37-9bd5-03627909e492
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: web
      k8s.kuboard.cn/name: app-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: web
        k8s.kuboard.cn/name: app-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: staffjoy-config
          image: 'registry.cn-hangzhou.aliyuncs.com/dypc/staffjoy-app-spa:1.0'
          imagePullPolicy: IfNotPresent
          name: staffjoy-app-svc
          ports:
            - containerPort: 80
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-12-12T14:39:51Z'
      lastUpdateTime: '2020-12-12T14:39:51Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-12-12T14:39:50Z'
      lastUpdateTime: '2020-12-12T14:39:51Z'
      message: ReplicaSet "app-service-84cf48b967" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/workload: app-service
  creationTimestamp: '2020-12-12T14:39:50Z'
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: app-service
  name: app-service
  namespace: staffjoy
  resourceVersion: '629594'
  selfLink: /api/v1/namespaces/staffjoy/services/app-service
  uid: e7b9b404-c944-43d5-977a-f1ba09164b70
spec:
  clusterIP: 10.244.67.95
  ports:
    - name: nht8np
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: app-service
  sessionAffinity: None
  type: ClusterIP

