---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    k8s.kuboard.cn/ingress: 'false'
    k8s.kuboard.cn/service: ClusterIP
    k8s.kuboard.cn/workload: bot-service
  creationTimestamp: '2020-12-12T12:18:32Z'
  generation: 1
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: bot-service
  name: bot-service
  namespace: staffjoy
  resourceVersion: '629019'
  selfLink: /apis/apps/v1/namespaces/staffjoy/deployments/bot-service
  uid: c0f55c2f-d7fe-4287-a8d3-cb542ad0d235
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: svc
      k8s.kuboard.cn/name: bot-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: svc
        k8s.kuboard.cn/name: bot-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: staffjoy-config
          image: 'registry.cn-hangzhou.aliyuncs.com/dypc/staffjoy-bot-svc:1.0'
          imagePullPolicy: IfNotPresent
          name: staffjoy-bot-svc
          ports:
            - containerPort: 80
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-12-12T12:18:32Z'
      lastUpdateTime: '2020-12-12T12:18:33Z'
      message: ReplicaSet "bot-service-56bd8cbd85" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2020-12-12T14:35:42Z'
      lastUpdateTime: '2020-12-12T14:35:42Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/workload: bot-service
  creationTimestamp: '2020-12-12T12:18:32Z'
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: bot-service
  name: bot-service
  namespace: staffjoy
  resourceVersion: '621679'
  selfLink: /api/v1/namespaces/staffjoy/services/bot-service
  uid: 0a941486-6e3b-4370-9630-66d18601c98b
spec:
  clusterIP: 10.244.3.141
  ports:
    - name: expfgi
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: bot-service
  sessionAffinity: None
  type: ClusterIP

