---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    k8s.kuboard.cn/ingress: 'false'
    k8s.kuboard.cn/service: ClusterIP
    k8s.kuboard.cn/workload: company-service
  creationTimestamp: '2020-12-12T12:11:50Z'
  generation: 1
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: company-service
  name: company-service
  namespace: staffjoy
  resourceVersion: '620726'
  selfLink: /apis/apps/v1/namespaces/staffjoy/deployments/company-service
  uid: 0ee5e38a-7a3d-4bd4-9f2b-b92623fb3e59
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: svc
      k8s.kuboard.cn/name: company-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: svc
        k8s.kuboard.cn/name: company-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: staffjoy-config
          image: 'registry.cn-hangzhou.aliyuncs.com/dypc/staffjoy-company-svc:1.0'
          imagePullPolicy: IfNotPresent
          name: staffjoy-company-svc
          ports:
            - containerPort: 80
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-12-12T12:11:52Z'
      lastUpdateTime: '2020-12-12T12:11:52Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-12-12T12:11:50Z'
      lastUpdateTime: '2020-12-12T12:11:52Z'
      message: ReplicaSet "company-service-677957c6d7" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/workload: company-service
  creationTimestamp: '2020-12-12T12:11:50Z'
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: company-service
  name: company-service
  namespace: staffjoy
  resourceVersion: '620699'
  selfLink: /api/v1/namespaces/staffjoy/services/company-service
  uid: 8fc5e4c5-2d02-45ff-a00b-63e07bd06eae
spec:
  clusterIP: 10.244.41.35
  ports:
    - name: dd53wp
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: company-service
  sessionAffinity: None
  type: ClusterIP

