---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    k8s.kuboard.cn/ingress: 'false'
    k8s.kuboard.cn/service: NodePort
    k8s.kuboard.cn/workload: faraday-service
  creationTimestamp: '2020-12-11T10:23:48Z'
  generation: 2
  labels:
    k8s.kuboard.cn/layer: gateway
    k8s.kuboard.cn/name: faraday-service
  name: faraday-service
  namespace: staffjoy
  resourceVersion: '633032'
  selfLink: /apis/apps/v1/namespaces/staffjoy/deployments/faraday-service
  uid: e006afe6-6355-4e26-94ce-95a617813195
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: gateway
      k8s.kuboard.cn/name: faraday-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2020-12-12T23:03:55+08:00'
      labels:
        k8s.kuboard.cn/layer: gateway
        k8s.kuboard.cn/name: faraday-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: staffjoy-config
          image: 'registry.cn-hangzhou.aliyuncs.com/dypc/staffjoy-faraday:1.0'
          imagePullPolicy: IfNotPresent
          name: staffjoy-faraday-svc
          ports:
            - containerPort: 80
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-12-11T10:23:50Z'
      lastUpdateTime: '2020-12-11T10:23:50Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-12-11T10:23:48Z'
      lastUpdateTime: '2020-12-12T15:03:57Z'
      message: ReplicaSet "faraday-service-68b88586b5" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/workload: faraday-service
  creationTimestamp: '2020-12-11T10:23:48Z'
  labels:
    k8s.kuboard.cn/layer: gateway
    k8s.kuboard.cn/name: faraday-service
  name: faraday-service
  namespace: staffjoy
  resourceVersion: '555387'
  selfLink: /api/v1/namespaces/staffjoy/services/faraday-service
  uid: 07242747-f9e8-4121-a8fa-ba82485bb08a
spec:
  clusterIP: 10.244.29.232
  externalTrafficPolicy: Cluster
  ports:
    - name: 2absch
      nodePort: 30001
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s.kuboard.cn/layer: gateway
    k8s.kuboard.cn/name: faraday-service
  sessionAffinity: None
  type: NodePort

