---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    k8s.kuboard.cn/ingress: 'false'
    k8s.kuboard.cn/service: ClusterIP
    k8s.kuboard.cn/workload: myaccount-service
  creationTimestamp: '2020-12-12T14:41:00Z'
  generation: 1
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: myaccount-service
  name: myaccount-service
  namespace: staffjoy
  resourceVersion: '629805'
  selfLink: /apis/apps/v1/namespaces/staffjoy/deployments/myaccount-service
  uid: 5870ff96-aa40-45c5-b11b-fd122e9f0c01
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: web
      k8s.kuboard.cn/name: myaccount-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: web
        k8s.kuboard.cn/name: myaccount-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: staffjoy-config
          image: 'registry.cn-hangzhou.aliyuncs.com/dypc/staffjoy-myaccount-spa:1.0'
          imagePullPolicy: IfNotPresent
          name: staffjoy-myaccount-svc
          ports:
            - containerPort: 80
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-12-12T14:41:01Z'
      lastUpdateTime: '2020-12-12T14:41:01Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-12-12T14:41:00Z'
      lastUpdateTime: '2020-12-12T14:41:01Z'
      message: ReplicaSet "myaccount-service-c4f675cd5" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/workload: myaccount-service
  creationTimestamp: '2020-12-12T14:41:00Z'
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: myaccount-service
  name: myaccount-service
  namespace: staffjoy
  resourceVersion: '629781'
  selfLink: /api/v1/namespaces/staffjoy/services/myaccount-service
  uid: 16635635-f37e-4762-81d9-1b8a41bda918
spec:
  clusterIP: 10.244.198.100
  ports:
    - name: msbpi7
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: myaccount-service
  sessionAffinity: None
  type: ClusterIP

