---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    k8s.kuboard.cn/ingress: 'false'
    k8s.kuboard.cn/service: ClusterIP
    k8s.kuboard.cn/workload: whoami-service
  creationTimestamp: '2020-12-12T12:13:15Z'
  generation: 1
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: whoami-service
  name: whoami-service
  namespace: staffjoy
  resourceVersion: '620947'
  selfLink: /apis/apps/v1/namespaces/staffjoy/deployments/whoami-service
  uid: 63c68ce3-0756-4c6f-a746-687117af27bb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: svc
      k8s.kuboard.cn/name: whoami-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: svc
        k8s.kuboard.cn/name: whoami-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: staffjoy-config
          image: 'registry.cn-hangzhou.aliyuncs.com/dypc/staffjoy-whoami-svc:1.0'
          imagePullPolicy: IfNotPresent
          name: staffjoy-whoami-svc
          ports:
            - containerPort: 80
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-12-12T12:13:17Z'
      lastUpdateTime: '2020-12-12T12:13:17Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-12-12T12:13:15Z'
      lastUpdateTime: '2020-12-12T12:13:17Z'
      message: ReplicaSet "whoami-service-86f4485855" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/workload: whoami-service
  creationTimestamp: '2020-12-12T12:13:15Z'
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: whoami-service
  name: whoami-service
  namespace: staffjoy
  resourceVersion: '620926'
  selfLink: /api/v1/namespaces/staffjoy/services/whoami-service
  uid: 03de9038-c485-4986-98c2-46d42d2fc7d9
spec:
  clusterIP: 10.244.244.86
  ports:
    - name: rz3bka
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: whoami-service
  sessionAffinity: None
  type: ClusterIP

