---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    k8s.kuboard.cn/ingress: 'false'
    k8s.kuboard.cn/service: ClusterIP
    k8s.kuboard.cn/workload: www-service
  creationTimestamp: '2020-12-12T12:47:09Z'
  generation: 1
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: www-service
  name: www-service
  namespace: staffjoy
  resourceVersion: '629004'
  selfLink: /apis/apps/v1/namespaces/staffjoy/deployments/www-service
  uid: cd0caf95-8d2f-47ff-b34f-3eb6936c43e7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: web
      k8s.kuboard.cn/name: www-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: web
        k8s.kuboard.cn/name: www-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: staffjoy-config
          image: 'registry.cn-hangzhou.aliyuncs.com/dypc/staffjoy-web-app:1.0'
          imagePullPolicy: IfNotPresent
          name: staffjoy-www-svc
          ports:
            - containerPort: 80
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-12-12T12:47:09Z'
      lastUpdateTime: '2020-12-12T12:47:10Z'
      message: ReplicaSet "www-service-58779b6999" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2020-12-12T14:35:40Z'
      lastUpdateTime: '2020-12-12T14:35:40Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/workload: www-service
  creationTimestamp: '2020-12-12T12:47:09Z'
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: www-service
  name: www-service
  namespace: staffjoy
  resourceVersion: '625414'
  selfLink: /api/v1/namespaces/staffjoy/services/www-service
  uid: 158a4405-c1e5-44c7-b017-5efc36728937
spec:
  clusterIP: 10.244.3.122
  ports:
    - name: wq2fim
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: www-service
  sessionAffinity: None
  type: ClusterIP

